project_id = "cqauyygqjyxtnthasjzj"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.ai-tutor]
verify_jwt = false

[functions.delete-account]
verify_jwt = false